OTHER_FILES += \
extras/excludedParts.lst \
extras/fadeStepColorParts.lst \
extras/freeformAnnotations.lst \
extras/LDConfig.ldr \
extras/pli.mpd \
extras/pliSubstituteParts.lst \
extras/povray.ini \
extras/titleAnnotations.lst \
extras/ldglite.ini \
extras/nativePOV.ini \
docs/COPYING_BRIEF \
docs/CREDITS.txt \
docs/lpub3d.1 \
docs/README.txt \
docs/RELEASE_NOTES.html \
../builds/check/build_checks.bat \
../builds/check/build_checks.sh \
../builds/check/build_checks.mpd \
../builds/linux/CreateDeb.sh \
../builds/linux/CreatePkg.sh \
../builds/linux/CreateRpm.sh \
../builds/linux/docker-compose/docker-compose-cibuild-linux.yml \
../builds/linux/docker-compose/dockerfiles/Dockerfile-cibuild-archlinux \
../builds/linux/docker-compose/dockerfiles/Dockerfile-cibuild-fedora \
../builds/linux/docker-compose/dockerfiles/Dockerfile-cibuild-ubuntu \
../builds/linux/obs/alldeps/appimage.yml \
../builds/linux/obs/alldeps/debian/changelog \
../builds/linux/obs/alldeps/debian/control \
../builds/linux/obs/alldeps/debian/lpub3d.dsc \
../builds/linux/obs/alldeps/GetLocalLibs.sh \
../builds/linux/obs/alldeps/GetQt5Libs.sh \
../builds/linux/obs/alldeps/lpub3d.spec \
../builds/linux/obs/alldeps/PKGBUILD \
../builds/linux/obs/debian/changelog \
../builds/linux/obs/debian/compat \
../builds/linux/obs/debian/control \
../builds/linux/obs/debian/copyright \
../builds/linux/obs/debian/lpub3d.dsc \
../builds/linux/obs/debian/postinst \
../builds/linux/obs/debian/postrm \
../builds/linux/obs/debian/lpub3d.lintian-overrides \
../builds/linux/obs/debian/rules \
../builds/linux/obs/debian/source/format \
../builds/linux/obs/debian/source/include-binaries \
../builds/linux/obs/lpub3d-rpmlintrc \
../builds/linux/obs/lpub3d.spec \
../builds/linux/obs/PKGBUILD \
../builds/linux/obs/_service \
../builds/macx/CreateDmg.sh \
../builds/utilities/mesa/build_osmesa.sh \
../builds/utilities/mesa/glu.spec \
../builds/utilities/mesa/Mesa.spec \
../builds/utilities/mesa/osmesa-config \
../builds/utilities/ci/dropbox_uploader.sh \
../builds/utilities/ci/sfdeploy.sh \
../builds/utilities/ci/travis/after_script \
../builds/utilities/ci/travis/before_install \
../builds/utilities/ci/travis/before_script \
../builds/utilities/ci/travis/install \
../builds/utilities/ci/travis/prepare_store \
../builds/utilities/ci/travis/releases \
../builds/utilities/ci/travis/script \
../builds/utilities/cleanup.bat \
../builds/utilities/Copyright-Source-Header.txt \
../builds/utilities/create-dmg \
../builds/utilities/CreateRenderers.bat \
../builds/utilities/CreateRenderers.sh \
../builds/utilities/dmg-utils/dmg-fileicon \
../builds/utilities/dmg-utils/dmg-license.py \
../builds/utilities/dmg-utils/template.applescript \
../builds/utilities/hooks/pre-commit \
../builds/utilities/json/complete.json \
../builds/utilities/json/lpub3dldrawunf.json \
../builds/utilities/json/lpub3dupdates.json \
../builds/utilities/mesa/buildosmesa.sh \
../builds/utilities/mesa/glu.spec \
../builds/utilities/mesa/Mesa.spec \
../builds/utilities/mesa/osmesa-config \
../builds/utilities/nsis-scripts/AppVersion.nsh \
../builds/utilities/nsis-scripts/Include/NsisMultiUser.nsh \
../builds/utilities/nsis-scripts/Include/Registry.nsh \
../builds/utilities/nsis-scripts/Include/UAC.nsh \
../builds/utilities/nsis-scripts/Include/Utils.nsh \
../builds/utilities/nsis-scripts/LPub3DInstallFiles.nsh \
../builds/utilities/nsis-scripts/LPub3DNoPack.nsi \
../builds/utilities/nsis-scripts/LPub3DUninstallFiles.nsh \
../builds/utilities/nsis-scripts/Uninstall.nsh \
../builds/utilities/README.md \
../builds/utilities/set-ldrawdir.command \
../builds/utilities/update-config-files.bat \
../builds/utilities/update-config-files.sh \
../builds/utilities/version.info \
../builds/windows/AutoBuild.cmd \
../builds/windows/CreateExePkg.cmd \
../.github/ISSUE_TEMPLATE.md
