OTHER_FILES += \
    $$PWD/$$lower($$MAN_PAGE) \
    $$PWD/Info.plist \
    $$PWD/lpub3d.1 \
    $$PWD/lpub3d.sh \
    $$PWD/lpub3d.xml \
    $$PWD/lpub3d.desktop \
    $$PWD/lpub3d.appdata.xml \
    $$PWD/extras/excludedParts.lst \
    $$PWD/extras/fadeStepColorParts.lst \
    $$PWD/extras/freeformAnnotations.lst \
    $$PWD/extras/LDConfig.ldr \
    $$PWD/extras/pli.mpd \
    $$PWD/extras/pliSubstituteParts.lst \
    $$PWD/extras/titleAnnotations.lst \
    $$PWD/extras/ldglite.ini \
    $$PWD/extras/ldvExport.ini \
    $$PWD/extras/LPub3D_Npp_UDL.xml \
    $$PWD/docs/COPYING_BRIEF \
    $$PWD/docs/CREDITS.txt \
    $$PWD/docs/lpub3d.1 \
    $$PWD/docs/README.txt \
    $$PWD/docs/RELEASE_NOTES.html \
    $$PWD/resources/builtincommanddescriptions.json \
    $$PWD/resources/builtinsnippets.json \
    $$PWD/../.gitignore \
    $$PWD/../.travis.yml \
    $$PWD/../appveyor.yml \
    $$PWD/../snapcraft.yaml \
    $$PWD/../README.md \
    $$PWD/../builds/check/build_checks.bat \
    $$PWD/../builds/check/build_checks.sh \
    $$PWD/../builds/check/build_checks.mpd \
    $$PWD/../builds/linux/CreateDeb.sh \
    $$PWD/../builds/linux/CreateLinuxMulitArch.sh \
    $$PWD/../builds/linux/CreatePkg.sh \
    $$PWD/../builds/linux/CreateRpm.sh \
    $$PWD/../builds/linux/docker-compose/docker-compose-cibuild-linux.yml \
    $$PWD/../builds/linux/docker-compose/dockerfiles/Dockerfile-cibuild-archlinux \
    $$PWD/../builds/linux/docker-compose/dockerfiles/Dockerfile-cibuild-fedora \
    $$PWD/../builds/linux/docker-compose/dockerfiles/Dockerfile-cibuild-ubuntu \
    $$PWD/../builds/linux/obs/alldeps/appimage.yml \
    $$PWD/../builds/linux/obs/alldeps/debian/changelog \
    $$PWD/../builds/linux/obs/alldeps/debian/control \
    $$PWD/../builds/linux/obs/alldeps/debian/lpub3d.dsc \
    $$PWD/../builds/linux/obs/alldeps/GetLocalLibs.sh \
    $$PWD/../builds/linux/obs/alldeps/GetQt5Libs.sh \
    $$PWD/../builds/linux/obs/alldeps/LcLibPCH.sh \
    $$PWD/../builds/linux/obs/alldeps/lpub3d.spec \
    $$PWD/../builds/linux/obs/alldeps/PKGBUILD \
    $$PWD/../builds/linux/obs/debian/changelog \
    $$PWD/../builds/linux/obs/debian/compat \
    $$PWD/../builds/linux/obs/debian/control \
    $$PWD/../builds/linux/obs/debian/copyright \
    $$PWD/../builds/linux/obs/debian/lpub3d.dsc \
    $$PWD/../builds/linux/obs/debian/postinst \
    $$PWD/../builds/linux/obs/debian/postrm \
    $$PWD/../builds/linux/obs/debian/lpub3d.lintian-overrides \
    $$PWD/../builds/linux/obs/debian/rules \
    $$PWD/../builds/linux/obs/debian/source/format \
    $$PWD/../builds/linux/obs/debian/source/include-binaries \
    $$PWD/../builds/linux/obs/lpub3d-rpmlintrc \
    $$PWD/../builds/linux/obs/lpub3d.spec \
    $$PWD/../builds/linux/obs/PKGBUILD \
    $$PWD/../builds/linux/obs/_service \
    $$PWD/../builds/macx/CreateDmg.sh \
    $$PWD/../builds/utilities/mesa/build_osmesa.sh \
    $$PWD/../builds/utilities/mesa/glu.spec \
    $$PWD/../builds/utilities/mesa/Mesa.spec \
    $$PWD/../builds/utilities/mesa/osmesa-config \
    $$PWD/../builds/utilities/ci/dropbox_uploader.sh \
    $$PWD/../builds/utilities/ci/ci_cutover.sh \
    $$PWD/../builds/utilities/ci/next_cutover.sh \
    $$PWD/../builds/utilities/ci/sfdeploy.sh \
    $$PWD/../builds/utilities/ci/dropbox_uploader.sh \
    $$PWD/../builds/utilities/ci/travis/after_script \
    $$PWD/../builds/utilities/ci/travis/before_install \
    $$PWD/../builds/utilities/ci/travis/before_script \
    $$PWD/../builds/utilities/ci/travis/install \
    $$PWD/../builds/utilities/ci/travis/prepare_store \
    $$PWD/../builds/utilities/ci/travis/releases \
    $$PWD/../builds/utilities/ci/travis/script \
    $$PWD/../builds/utilities/ci/github/linux-amd64-build.sh \
    $$PWD/../builds/utilities/ci/github/linux-build.sh \
    $$PWD/../builds/utilities/ci/github/build-deploy.sh \
    $$PWD/../builds/utilities/ci/github/linux-multiarch-build.sh \
    $$PWD/../builds/utilities/ci/github/macos-build.sh \
    $$PWD/../builds/utilities/ci/github/windows-build.bat \
    $$PWD/../builds/utilities/cleanup.bat \
    $$PWD/../builds/utilities/Copyright-Source-Header.txt \
    $$PWD/../builds/utilities/CreateRenderers.bat \
    $$PWD/../builds/utilities/CreateRenderers.sh \
    $$PWD/../builds/utilities/dmg-utils/create-dmg \
    $$PWD/../builds/utilities/dmg-utils/.this-is-the-repo-sentinel-file \
    $$PWD/../builds/utilities/dmg-utils/support/template.applescript \
    $$PWD/../builds/utilities/dmg-utils/support/eula-resources-template.xml \
    $$PWD/../builds/utilities/hooks/pre-commit \
    $$PWD/../builds/utilities/json/complete.json \
    $$PWD/../builds/utilities/json/lpub3dldrawunf.json \
    $$PWD/../builds/utilities/json/lpub3dupdates.json \
    $$PWD/../builds/utilities/mesa/build_osmesa.sh \
    $$PWD/../builds/utilities/mesa/glu.spec \
    $$PWD/../builds/utilities/mesa/Mesa.spec \
    $$PWD/../builds/utilities/mesa/osmesa-config \
    $$PWD/../builds/utilities/mesa/PKGBUILD \
    $$PWD/../builds/utilities/nsis-scripts/AppVersion.nsh \
    $$PWD/../builds/utilities/nsis-scripts/Include/NsisMultiUser.nsh \
    $$PWD/../builds/utilities/nsis-scripts/Include/Registry.nsh \
    $$PWD/../builds/utilities/nsis-scripts/Include/UAC.nsh \
    $$PWD/../builds/utilities/nsis-scripts/Include/Utils.nsh \
    $$PWD/../builds/utilities/nsis-scripts/LPub3DInstallFiles.nsh \
    $$PWD/../builds/utilities/nsis-scripts/LPub3DNoPack.nsi \
    $$PWD/../builds/utilities/nsis-scripts/LPub3DUninstallFiles.nsh \
    $$PWD/../builds/utilities/nsis-scripts/Uninstall.nsh \
    $$PWD/../builds/utilities/GetWindowsOpenSSL.bat \
    $$PWD/../builds/utilities/README.md \
    $$PWD/../builds/utilities/RunCreate.sh \
    $$PWD/../builds/utilities/set-ldrawdir.command \
    $$PWD/../builds/utilities/update-config-files.bat \
    $$PWD/../builds/utilities/update-config-files.sh \
    $$PWD/../builds/utilities/version.info \
    $$PWD/../builds/utilities/win_tee.cmd \
    $$PWD/../builds/windows/AutoBuild.bat \
    $$PWD/../builds/windows/CreateExePkg.bat \
    $$PWD/../builds/windows/RunBuildCheck.bat \
    $$PWD/../.github/ISSUE_TEMPLATE/1.issue_ticket.md \
    $$PWD/../.github/ISSUE_TEMPLATE/2.feature_request_ticket.md \
    $$PWD/../.github/workflows/prod_ci_build.yml \
    $$PWD/../.github/workflows/codeql.yml

DISTFILES += \
    $$PWD/ldraw_document.icns \
    $$PWD/lpub3d.icns
