FROM ubuntu:focal
ARG DEBIAN_FRONTEND=noninteractive
LABEL maintainer "Trevor SANDY <trevor.sandy@gmail.com>"
RUN apt-get update; apt-get install -y apt-utils desktop-file-utils dialog nautilus build-essential debhelper fakeroot ccache lsb-release
RUN apt-get install -y autotools-dev autoconf pkg-config libtool gdb curl gedit git wget unzip lintian
RUN apt-get install -y xvfb dos2unix qtcreator valgrind
RUN apt-get install -y lubuntu-desktop lightdm
RUN apt-get install -y locales
RUN rm /run/reboot-required*
RUN rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8
RUN apt-get install -y sudo \
    && groupadd -r user -g 1000 \
    && useradd -u 1000 -r -g user -m -d /user -c "Build pkg user" user \
    && chmod 755 /user \
    && echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user
RUN echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
RUN echo "\
[LightDM]\n\
[Seat:*]\n\
type=xremote\n\
xserver-hostname=host.docker.internal\n\
xserver-display-number=0\n\
autologin-user=user\n\
autologin-user-timeout=0\n\
autologin-session=Lubuntu\n\
" > /etc/lightdm/lightdm.conf.d/lightdm.conf
WORKDIR /user
USER user
VOLUME ["/buildpkg", "/user/projects", "/user/resources"]
ENV DISPLAY=host.docker.internal:0.0
CMD sudo service dbus start ; sudo service lightdm start

: <<'BLOCK_COMMENT'
Trevor SANDY
Last Update Jun 23, 2022
Copyright (C) 2022 - 2024 by Trevor SANDY

Run full Ubuntu desktop GUI in a Docker container displayed on Windows using (XServer)

Prerequisite installations:
1. WSL2
2. Docker Desktop
3. VcXsrv

Windows commands - run from <user>\Projects with this file placed at <user>\Projects\Dockerfiles
1. build command (Powershell):
> docker build -f ./Dockerfiles/Dockerfile-xsrv-lubuntu_focal -t trevorsandy-dev/xsrv-lubuntu:focal-amd64 .
2. launch VcXsrv from application
select 'One large window'
3. run command (Docker Desktop):
click run button and add following configuration
container name: xsrv-lubuntu
volume 01: (host) C:\Users\Trevor\Projects\Working\Docker-output\buildpkg /buildpkg
volume 02: (host) C:\Users\Trevor\Projects\Working\Docker-output          /user/resources
volume 03: (host) C:\Users\Trevor\Projects                                /user/projects
3. run command (Powershell):
> docker run -it -v ./Working/Docker-output/buildpkg:/buildpkg -v .:/user/projects xsrv-lubuntu /bin/bash

Run the following command or cut, paste and uncomment into a script

#!/bin/bash

export PRESERVE=true # set to true to preserve locally cloned repository
if test "${PRESERVE}" != "true"; then wget https://raw.githubusercontent.com/trevorsandy/lpub3d/master/builds/linux/CreateDeb.sh; fi && \
export DOCKER=true && \
export LP3D_ARCH=amd64 && \
export DEB_EXTENSION=amd64.deb && \
chmod a+x CreateDeb.sh && \
./CreateDeb.sh && \
if test -d /buildpkg; then \
  sudo cp -f /user/debbuild/*.deb /buildpkg/; \
  sudo cp -f /user/debbuild/*.ddeb /buildpkg/; \
  sudo cp -f /user/debbuild/*.dsc /buildpkg/; \
  sudo cp -f /user/debbuild/*.changes /buildpkg/; \
  sudo cp -f /user/debbuild/*.sha512 /buildpkg/; \
  sudo cp -f /user/debbuild/*.log /buildpkg/; \
  sudo cp -f /user/*.log /buildpkg/; \
  sudo cp -f /user/*.sh /buildpkg/; \
fi
BLOCK_COMMENT

