#ifndef __LDLUSERDEFAULTSKEYS_H__
#define __LDLUSERDEFAULTSKEYS_H__

#define PRIMITIVE_SUBSTITUTION_KEY "AllowPrimitiveSubstitution"
#define AMBIENT_KEY "Ambient"
#define ANISO_LEVEL_KEY "AnisoLevel"
#define FSAA_MODE_KEY "Antialias"
#define AUTO_CROP_KEY "AutoCrop"
#define BACKGROUND_COLOR_KEY "BackgroundColor3"
#define BFC_KEY "BFC"
#define BLACK_HIGHLIGHTS_KEY "BlackHighlights"
#define BOTTOM_INCLUDE_KEY "BottomInclude"
#define BOTTOM_MARGIN_KEY "BottomMargin"
#define BOUNDING_BOXES_ONLY_KEY "BoundingBoxesOnly"
#define CAMERA_GLOBE_KEY "CameraGlobe"							// NO UI
#define CHECK_PART_TRACKER_KEY "CheckPartTracker"
#define CHECK_PART_UPDATE_WAIT_KEY "CheckPartUpdateWait"
#define CHECK_PART_WAIT_KEY "CheckPartWait"
#define CHROME_BRILLIANCE_KEY "ChromeBril"
#define CHROME_REFLECTION_KEY "ChromeRefl"
#define CHROME_ROUGHNESS_KEY "ChromeRoughness"
#define CHROME_SPECULAR_KEY "ChromeSpecular"
#define COMMAND_LINES_LIST_KEY "CommandLinesList"				// NO UI
#define CONDITIONAL_EDGE_LINES_KEY "ConditionalEdges"
#define CONDITIONAL_HIGHLIGHTS_KEY "ConditionalHighlights"
#define CURVE_QUALITY_KEY "CurveQuality"
#define CUSTOM_ASPECT_RATIO_KEY "CustomAspectRatio"
#define CUSTOM_COLORS_KEY "CustomColors"
#define CUTAWAY_ALPHA_KEY "CutawayAlpha"
#define CUTAWAY_MODE_KEY "CutawayMode"
#define CUTAWAY_THICKNESS_KEY "CutawayThickness"
#define DEFAULT_COLOR_KEY "DefaultColor3"
#define DEFAULT_LATITUDE_KEY "DefaultLatitude"
#define DEFAULT_LAT_LONG_KEY "DefaultLatLong"
#define DEFAULT_LONGITUDE_KEY "DefaultLongitude"
#define DIFFUSE_KEY "Diffuse"
#define MODEL_CENTER_KEY "ModelCenter"							// NO UI
#define MODEL_SIZE_KEY "ModelSize"								// NO UI
#define DEFAULT_MATRIX_KEY "DefaultMatrix"
#define DEFAULT_ZOOM_KEY "DefaultZoom"							// NO UI
#define DRAW_EDGES_KEY "Edges"
#define DRAW_LIGHT_DATS_KEY "DrawLightDats"
#define EDITOR_KEY "Editor"
#define EDGES_ONLY_KEY "EdgesOnly"
#define EDGE_RADIUS_KEY "EdgeRadius"
#define EDGE_THICKNESS_KEY "EdgeThickness"
#define EXAMINE_MODE_KEY "ExamineMode"
#define EXPORT_FILE_KEY "ExportFile"
#define EXPORT_FILES_KEY "ExportFiles"						// NO UI
#define EXPORT_FILES_LIST_KEY "ExportFilesList"					// NO UI
#define EXPORT_SUFFIX_KEY "ExportSuffix"
#define EXPORTS_DIR_KEY "ExportsDir"
#define EXPORTS_DIR_MODE_KEY "ExportsDirMode"
#define EXTRA_SEARCH_DIRS_KEY "ExtraSearchDirs"
#define FOV_KEY "FOV"
#define FIND_REPLACEMENTS_KEY "FindReplacements"
#define FILE_VERSION_KEY "FileVersion"
#define FULLSCREEN_DEPTH_KEY "FullscreenDepth"
#define FULLSCREEN_HEIGHT_KEY "FullscreenHeight"
#define FULLSCREEN_REFRESH_KEY "FullscreenRefresh"
#define FULLSCREEN_WIDTH_KEY "FullscreenWidth"
#define GREEN_FRONT_FACES_KEY "GreenFrontFaces"
#define HIDE_STUDS_KEY "HideStuds"
#define HI_RES_PRIMITIVES_KEY "HiResPrimitives"
#define IGNORE_ALL_OGL_EXTENSIONS "IgnoreAllOGLExtensions"
#define IGNORE_ANISO_KEY "IgnoreAniso"
#define IGNORE_FRAMEBUFFER_OBJECT_KEY "IgnoreFramebufferObject"
#define IGNORE_MULTI_DRAW_ARRAYS_KEY "IgnoreMultiDrawArrays"
#define IGNORE_MULTISAMPLE_KEY "IgnoreMultisample"
#define IGNORE_MS_FILTER_HINT_KEY "IgnoreMultisampleFilterHint"
#define IGNORE_PBUFFER_KEY "IgnorePBuffer"
#define IGNORE_PIXEL_FORMAT_KEY "IgnorePixelFormat"
#define IGNORE_VAR_KEY "IgnoreVAR"
#define IGNORE_VBO_KEY "IgnoreVBO"
#define INLINE_POV_KEY "InlinePov"
#define INSTALL_PATH_KEY "InstallPath"							// NO UI
#define INSTALL_PATH_4_1_KEY "InstallPath 4.1"					// NO UI
#define INV_EXTERNAL_CSS_KEY "InventoryExternalCss"
#define INV_PART_IMAGES_KEY "InventoryPartImages"
#define INV_SHOW_FILE_KEY "InventoryShowFile"
#define INV_SHOW_MODEL_KEY "InventoryShowModel"
#define LAST_OPEN_PATH_KEY "LastOpenPath"
#define LDRAWDIR_KEY "LDrawDir"
#define LDCONFIG_KEY "LDConfig"
#define LEFT_MARGIN_KEY "LeftMargin"
#define LIGHTING_KEY "Lighting"
#define LIGHT_VECTOR_KEY "LightVector"
#define LINE_SMOOTHING_KEY "LineSmoothing"
#define MAX_RECENT_FILES_KEY "MaxRecentFiles"
#define MEMORY_USAGE_KEY "MemoryUsage"
#define MULTI_THREADED_KEY "MultiThreaded"
#define NO_LIGHT_GEOM_KEY "NoLightGeom"
#define ONE_LIGHT_KEY "OneLight"
#define OPTIONAL_STANDARD_LIGHT_KEY "OptionalStandardLight"
#define ORIENTATION_KEY "Orientation"
#define PAPER_SIZE_KEY "PaperSize"
#define PARTS_LISTS_DIR_KEY "PartsListsDir"
#define PARTS_LISTS_DIR_MODE_KEY "PartsListsDirMode"
#define PERFORM_SMOOTHING_KEY "PerformSmoothing"
#define PHONG_KEY "Phong"
#define PHONG_SIZE_KEY "PhongSize"
#define POLL_KEY "Poll"
#define POLYGON_OFFSET_KEY "PolygonOffset"
#define POV_CAMERA_ASPECT_KEY "PovCameraAspect"
#define PRINT_BACKGROUND_KEY "PrintBackground"
#define PROCESS_LDCONFIG_KEY "ProcessLDConfig"
#define PROXY_PORT_KEY "ProxyPort"
#define PROXY_SERVER_KEY "ProxyServer"
#define PROXY_TYPE_KEY "ProxyType"
#define RECENT_FILES_KEY "RecentFiles"
#define RED_BACK_FACES_KEY "RedBackFaces"
#define REFLECTION_KEY "Refl"
#define REFLECTIONS_KEY "Reflections"
#define REMOVE_HIDDEN_LINES_KEY "RemoveHiddenLines"
#define RIGHT_MARGIN_KEY "RightMargin"
#define RUBBER_PHONG_KEY "RubberPhong"
#define RUBBER_PHONG_SIZE_KEY "RubberPhongSize"
#define RUBBER_REFLECTION_KEY "RubberRefl"
#define SAVE_ACTUAL_SIZE_KEY "SaveActualSize"
#define SAVE_ALPHA_KEY "SaveAlpha"
#define SAVE_DIGITS_KEY "SaveDigits"
#define SAVE_DIR_KEY "SaveDir"
#define SAVE_HEIGHT_KEY "SaveHeight"
#define SAVE_IMAGE_TYPE_KEY "SaveImageType"
#define SAVE_MATCH_SCALE_FACTOR_KEY "SaveMatchScaleFactor"
#define SAVE_SCALE_FACTOR_KEY "SaveScaleFactor"					// NO UI
#define SAVE_SERIES_KEY "SaveSeries"
#define SAVE_SNAPSHOT_KEY "SaveSnapshot"						// NO UI
#define SAVE_SNAPSHOTS_KEY "SaveSnapshots"						// NO UI
#define SAVE_SNAPSHOTS_LIST_KEY "SaveSnapshotsList"				// NO UI
#define SAVE_STEPS_KEY "SaveSteps"
#define SAVE_STEPS_SAME_SCALE_KEY "SaveStepsSameScale"
#define SAVE_STEPS_SUFFIX_KEY "SaveStepsSuffix"
#define SAVE_WIDTH_KEY "SaveWidth"
#define SAVE_Z_MAP_KEY "SaveZMap"
#define SAVE_ZOOM_TO_FIT_KEY "SaveZoomToFit"
#define SEAMS_KEY "Seams"
#define SEAM_WIDTH_KEY "SeamWidth"
#define SELECTED_ASPECT_RATIO_KEY "SelectedAspectRatio"
#define SHADOWS_KEY "Shadows"
#define SHOW_ALL_TYPE5_KEY "ShowAllType5"
#define SHOW_AXES_KEY "ShowAxes"
#define SHOW_ERRORS_KEY "ShowErrors"
#define SHOW_FPS_KEY "ShowFPS"
#define SHOW_HIGHLIGHT_LINES_KEY "ShowHighlightLines"
#define SHOW_TYPE5_CONTROL_POINTS_KEY "ShowType5ControlPoints"
#define SHOW_WARNINGS_KEY "ShowWarnings"
#define SMOOTH_CURVES_KEY "SmoothCurves"
#define SNAPSHOTS_DIR_KEY "SnapshotsDir"
#define SNAPSHOTS_DIR_MODE_KEY "SnapshotsDirMode"
#define SNAPSHOT_SUFFIX_KEY "SnapshotSuffix"
#define SORT_KEY "SortTransparent"
#define STATUS_BAR_KEY "StatusBar"
#define STEP_KEY "Step"
#define STEREO_MODE_KEY "StereoMode"
#define STEREO_SPACING_KEY "StereoSpacing"
#define SUBDUED_LIGHTING_KEY "SubduedLighting"
#define TEXTURE_FILTER_TYPE_KEY "TextureFilterType"
#define TEXTURE_STUDS_KEY "TextureStuds"
#define TOOLBAR_KEY "Toolbar"
#define TOP_INCLUDE_KEY "TopInclude"
#define TOP_MARGIN_KEY "TopMargin"
#define TOPMOST_KEY "Topmost"
#define TRANS_DEFAULT_COLOR_KEY "TransDefaultColor"
#define TRANS_FILTER_KEY "TransFilter"
#define TRANS_REFLECTION_KEY "TransRefl"
#define TRANS_IOR_KEY "TransIoR"
#define FLAT_SHADING_KEY "UseFlatShading"
#define QUALITY_LIGHTING_KEY "UseQualityLighting"
#define QUALITY_STUDS_KEY "UseQualityStuds"
#define QUALITY_EXPORT_KEY "Quality"
#define SPECULAR_KEY "UseSpecular"
#define STIPPLE_KEY "UseStipple"
#define UNMIRROR_STUDS_KEY "UnmirrorStuds"
#define VERIFY_LDRAW_DIR_KEY "VerifyLDrawDir"
#define VIEW_MODE_KEY "ViewMode"
#define VISUAL_STYLE_ENABLED_KEY "VisualStyleEnabled"
#define WINDOW_HEIGHT_KEY "WindowHeight"
#define WINDOW_MAXIMIZED_KEY "WindowMaximized"
#define WINDOW_WIDTH_KEY "WindowWidth"
#define WIREFRAME_KEY "Wireframe"
#define WIREFRAME_FOG_KEY "WireframeFog"
#define WIREFRAME_THICKNESS_KEY "WireframeThickness"
#define XML_MAP_KEY "XmlMap"
#define XML_MAP_PATH_KEY "XmlMapPath"
#define ZOOM_MAX_KEY "ZoomMax"									// NO UI

// The following are undocumented, and should stay that way.
#define DEBUG_LEVEL_KEY "DebugLevel"
#define DEBUG_COMMAND_LINE_KEY "DebugCommandLine"
#define DEFAULT_COLOR_NUMBER_KEY "DefaultColorNumber"
#define HOT_KEYS_KEY "HotKeys"
#define PREFERENCE_SET_KEY "PreferenceSet"
#define PRINT_DPI_KEY "PrintDPI"								// NOT USED
#define USE_PRINTER_DPI_KEY "UsePrinterDPI"						// NOT USED
#define LAST_LIBRARY_UPDATE_KEY "LastLibraryUpdate"

// The following was added to improve load performance.  Since it didn't really
// help much, I decided not to publicize it, so it will probably never be
// documented.
#define SKIP_VALIDATION_KEY "SkipValidation"

// The following is used to decide whether or not to show the part count total
// in the parts list.  It was decided to always show this, so it's going to
// remain undocumented.
#define INV_SHOW_TOTAL_KEY "InventoryShowTotal"

// The following are undocumented, but need to be documented.
#define PRINT_CUSTOM_DPI_KEY "PrintCustomDPI"
#define PRINT_ADJUST_EDGES_KEY "PrintAdjustEdges"
#define RANDOM_COLORS_KEY "RandomColors"
#define INV_OVERWRITE_SNAPSHOT_KEY "InventoryOverwriteSnapshot"
#define HDR_SNAPSHOTS_KEY "HDRSnapshots"
#define IGNORE_CLAMP_TO_BORDER "IgnoreClampToBorder"
#define TEXMAPS_KEY "Texmaps"
#define TEXTURES_AFTER_TRANSPARENT_KEY "TexturesAfterTransparent"
#define TEXTURE_OFFSET_FACTOR_KEY "TextureOffsetFactor"
#define FORCE_THEMED_MENUS_KEY "ForceThemedMenus"

#define OBI_KEY "OBI"
#define IGNORE_OCCLUSION_QUERY_KEY "IgnoreOcclusionQuery"
#define BLUE_NEUTRAL_FACES_KEY "BlueNeutralFaces"
#define KEEP_RIGHT_SIDE_UP_KEY "KeepRightSideUp"

// The following are undocumented, but perhaps need to be documented.
#define INV_LAST_SAVE_PATH_KEY "InventoryLastSavePath"
#define INV_COLUMN_ORDER_KEY "InventoryColumnOrder"
#define SS_SIZE_KEY "SSSize"
#define SS_SPEED_KEY "SSSpeed"
#define SS_ROTATION_SPEED_KEY "SSRotationSpeed"
#define SS_FILENAME_KEY "SSFilename"
#define SS_DIRECTORY_KEY "SSDirectory"
#define SS_LAST_OPEN_PATH_KEY "SSLastOpenPath"
#define SS_FILE_MODE_KEY "SSFileMode"
#define SS_SLEEP_WORKAROUND_KEY "SSSleepWorkaround"
#define SS_RANDOM_PREF_SET_KEY "SSRandomPrefSet"
#define HFOV_KEY "HFOV"
#define GL2PS_ALLOWED_KEY "GL2PSAllowed"
#define MODEL_TREE_OPTIONS_SHOWN_KEY "ModelTreeOptionsShown"
#define LAST_SNAPSHOT_DIR_KEY "LastSnapshotDir"
#define LAST_EXPORT_DIR_KEY "LastExportDir"
#define LAST_LAT_KEY "LastLat"
#define LAST_LON_KEY "LastLon"
#define LAST_HAVE_DIST_KEY "LastHaveDist"
#define LAST_DIST_KEY "LastDist"
#define SAVE_EXPORT_TYPE_KEY "SaveExportType"
#define MODEL_TREE_HIGHLIGHT_KEY "ModelTreeHighlight"
#define MAIN_TOOLBAR_IDS_KEY "MainToolbarIDs"
#define SHOW_MAIN_TOOLBAR_KEY "ShowMainToolbar"
#define SHOW_STEPS_TOOLBAR_KEY "ShowStepsToolbar"
#define MODEL_TREE_HIGHLIGHT_COLOR_KEY "ModelTreeHighlightColor"
#define MODEL_TREE_CUST_COLORS_KEY "ModelTreeDlg/CustomColor"
#define LOGFILE_KEY "Logfile"

#endif // __LDLUSERDEFAULTSKEYS_H__
