#!/bin/bash
#
# Travis-ci build [before_install] procedures
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: March 06, 2019
#  Copyright (c) 2017 - 2020 by Trevor SANDY
#
cd $LP3D_BUILD_FOLDER

export DISPLAY=:99.0
if [ "$TRAVIS_OS_NAME" = "osx" ]; then
  ( sudo Xvfb :99 -ac -screen 0 1024x768x24; echo ok ) &
fi
# give xvfb some time to start
sleep 3
