#!/bin/bash
#
# Travis-ci build [before_install] procedures
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: April 12, 2018
#  Copyright (c) 2017 - 2018 by Trevor SANDY
#
cd $LP3D_BUILD_FOLDER

export DISPLAY=:99.0
if [ "$TRAVIS_OS_NAME" = "linux" ]; then
  #sh -e /etc/init.d/xvfb start;
  /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  # Set to address 'QXcbConnection: Could not connect to display' message
  sudo ln -s /usr/share/fonts /usr/lib/x86_64-linux-gnu/fonts
  export QT_QPA_PLATFORM=offscreen
  export QT_QPA_FONTDIR=/usr/lib/x86_64-linux-gnu/fonts
fi
if [ "$TRAVIS_OS_NAME" = "osx" ]; then
  ( sudo Xvfb :99 -ac -screen 0 1024x768x24; echo ok ) &
fi
# give xvfb some time to start
sleep 3
