#!/bin/bash
#
# This commit-msg hook prevents secret files from being committed.
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: October 05, 2020
#  Copyright (c) 2017 - 2020 by Trevor SANDY
#
#  File: pre-commit-no-secrets
#
## Setup
## '>' denotes a new line
## cd to your git repository and type:
## $ cat << pbEOF >.git/hooks/pre-commit
## > #!/bin/sh
## > # Confirm master branch and set location of pre-commit script in your source repository
## > ./builds/utilities/hooks/pre-commit-no-secrets || true
## > pbEOF
## $
#
FILES_PATTERN='\.dropbox_oauth|\.github_api*|\.sfdeploy_travis*'
FORBIDDEN='secrets'
git diff --cached --name-only | \
    egrep "$FILES_PATTERN" && \
    echo " -Commit rejected - found $FORBIDDEN. Remove and try again" && echo && exit 1 || true